name: blocksim
channels:
- defaults
dependencies:
- asn1crypto=0.22.0
- ca-certificates=2017.08.26
- cachecontrol=0.12.3
- certifi=2017.7.27.1
- cffi=1.10.0
- chardet=3.0.4
- colorama=0.3.9
- cryptography=2.0.3
- distlib=0.2.5
- html5lib=0.999999999
- idna=2.6
- lockfile=0.12.2
- msgpack-python=0.4.8
- openssl=1.0.2l
- packaging=16.8
- pip=9.0.1
- progress=1.3
- pycparser=2.18
- pyopenssl=17.2.0
- pyparsing=2.2.0
- pysocks=1.6.7
- python=3.6.3
- requests=2.18.4
- setuptools=36.5.0
- six=1.11.0
- urllib3=1.22
- vc=14
- vs2015_runtime=14.0.25123
- webencodings=0.5.1
- wheel=0.29.0
- win_inet_pton=1.0.1
- wincertstore=0.2
